# Archivo de configuración para el pipeline de Leishmania
# ----------------------------------------------------

# Rutas a los datos de entrada
samples: "config/samples.tsv"
ref_genome: "data/reference/L_braziliensis_ref.fasta"

# Parámetros de herramientas
# Nombre de la base de datos de SnpEff para Leishmania braziliensis.
# ¡IMPORTANTE! Debes crearla o descargarla. El nombre suele ser el ID del genoma.
# Por ejemplo: 'TriTrypDB-46_LbraziliensisMHOMBR75M2904'
snpeff:
  database: "LbraziliensisMHOMBR75M2904" # Reemplazar con el nombre correcto de tu base de datos SnpEff
  path: "/path/to/your/snpeff/data" # Ruta a la carpeta 'data' de SnpEff si no es estándar
